#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -e

if [ "$1" = configure ] && [ -d /run/systemd/system ]; then
    systemctl daemon-reload || true
    if [ -z "$2" ]; then
        deb-systemd-helper enable pve-rclone-backupd.service >/dev/null || true
        systemctl start pve-rclone-backupd.service || true
    else
        deb-systemd-helper update-state pve-rclone-backupd.service >/dev/null || true
        systemctl try-restart pve-rclone-backupd.service || true
    fi
fi

exit 0
