// SPDX-License-Identifier: AGPL-3.0-or-later

// Command docgen generates the command-line reference of pve-rclone-backup
// from its command tree: Markdown pages for the documentation site and,
// with -man, manual pages for the package. Run it through `make docs`.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"github.com/spf13/pflag"

	"github.com/ariedotcodotnz/pve-rclone-backup/internal/cli"
)

// cliDir holds the generated Markdown reference, relative to the repository root.
const cliDir = "docs/reference/cli"

const generated = "<!-- Code generated by docgen from the pve-rclone-backup command tree. DO NOT EDIT; run make docs. -->\n"

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "fail if the reference is out of date instead of writing it")
	man := flag.String("man", "", "write manual pages to this directory instead of the Markdown reference")
	flag.Parse()

	if *man != "" {
		if err := genMan(commandTree(), *man); err != nil {
			fatal(err)
		}
		return
	}
	pages := genMarkdown(commandTree())
	dir := filepath.Join(*root, cliDir)
	existing, _ := filepath.Glob(filepath.Join(dir, "*.md"))
	stale := false
	for _, path := range existing {
		if _, ok := pages[filepath.Base(path)]; ok {
			continue
		}
		if *check {
			fmt.Fprintf(os.Stderr, "docgen: %s is no longer generated; run make docs\n", path)
			stale = true
		} else if err := os.Remove(path); err != nil {
			fatal(err)
		}
	}
	for name, content := range pages {
		path := filepath.Join(dir, name)
		if *check {
			if old, _ := os.ReadFile(path); !bytes.Equal(old, content) {
				fmt.Fprintf(os.Stderr, "docgen: %s is out of date; run make docs\n", path)
				stale = true
			}
			continue
		}
		if err := os.MkdirAll(dir, 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fatal(err)
		}
	}
	if stale {
		os.Exit(1)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "docgen:", err)
	os.Exit(1)
}

// commandTree returns the CLI's commands as a user sees them, including
// those cobra only adds when it executes a command line.
func commandTree() *cobra.Command {
	root := cli.New().Command()
	root.InitDefaultCompletionCmd()
	root.InitDefaultVersionFlag()
	root.DisableAutoGenTag = true
	return root
}

// genMan writes a manual page per command (section 1).
func genMan(root *cobra.Command, dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	// Reproducible: the date comes from the source, not the build.
	date := time.Unix(0, 0).UTC()
	if epoch := os.Getenv("SOURCE_DATE_EPOCH"); epoch != "" {
		var secs int64
		if _, err := fmt.Sscan(epoch, &secs); err != nil {
			return fmt.Errorf("SOURCE_DATE_EPOCH: %w", err)
		}
		date = time.Unix(secs, 0).UTC()
	}
	prepareForMan(root)
	return doc.GenManTree(root, &doc.GenManHeader{
		Title:   "PVE-RCLONE-BACKUP",
		Section: "1",
		Source:  "pve-rclone-backup",
		Manual:  "pve-rclone-backup manual",
		Date:    &date,
	}, dir)
}

// prepareForMan adapts the command tree to cobra's manual page generator,
// which reads help text as Markdown: placeholders such as <storage> would
// be dropped as HTML tags, so they are escaped. --help is left out, as in
// the Markdown reference.
func prepareForMan(c *cobra.Command) {
	md := strings.NewReplacer("<", `\<`, ">", `\>`)
	c.Use, c.Short, c.Long = md.Replace(c.Use), md.Replace(c.Short), md.Replace(c.Long)
	c.InitDefaultHelpFlag()
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		f.Usage = md.Replace(f.Usage)
		if f.Name == "help" {
			f.Hidden = true
		}
	})
	for _, s := range c.Commands() {
		prepareForMan(s)
	}
}

// genMarkdown returns the reference pages by file name: an index with the
// global options and a page per top-level command, which documents the
// command's whole subtree.
func genMarkdown(root *cobra.Command) map[string][]byte {
	pages := map[string][]byte{"index.md": indexPage(root)}
	for _, c := range subcommands(root) {
		pages[c.Name()+".md"] = commandPage(c)
	}
	return pages
}

func subcommands(c *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, s := range c.Commands() {
		if s.IsAvailableCommand() && !s.IsAdditionalHelpTopicCommand() {
			out = append(out, s)
		}
	}
	return out
}

func indexPage(root *cobra.Command) []byte {
	var b bytes.Buffer
	frontMatter(&b, "Command line")
	fmt.Fprintf(&b, "# %s\n\n", root.Name())
	description(&b, root)
	b.WriteString("Run the commands as root on a Proxmox VE node.\n\n")
	fmt.Fprintf(&b, "```\n%s <command> [flags]\n```\n\n", root.Name())

	b.WriteString("## Commands\n\n| Command | Description |\n|---|---|\n")
	for _, c := range subcommands(root) {
		fmt.Fprintf(&b, "| [`%s`](%s.md) | %s |\n", c.Name(), c.Name(), escape(c.Short))
	}

	b.WriteString("\n## Global options\n\nEvery command accepts these options.\n\n")
	b.WriteString(flagTable(root.Flags()))

	b.WriteString(`## Exit status

| Code | Meaning |
|---|---|
`)
	for _, e := range []struct {
		code    int
		meaning string
	}{
		{cli.ExitOK, "Success."},
		{cli.ExitError, "The command failed."},
		{cli.ExitUsage, "Usage error: an unknown command or flag, or invalid arguments."},
		{cli.ExitUnavailable, "The daemon cannot be reached."},
		{cli.ExitIncompatible, "The command line tool and the daemon speak incompatible API versions."},
		{cli.ExitFindings, "The command completed and found problems (`doctor`, `recover`, `recovery-kit verify`)."},
	} {
		fmt.Fprintf(&b, "| %d | %s |\n", e.code, e.meaning)
	}
	return b.Bytes()
}

func commandPage(c *cobra.Command) []byte {
	var b bytes.Buffer
	frontMatter(&b, c.Name())
	fmt.Fprintf(&b, "# %s\n\n", c.CommandPath())
	description(&b, c)
	usage(&b, c)
	if subs := subcommands(c); len(subs) > 0 {
		b.WriteString("| Command | Description |\n|---|---|\n")
		for _, s := range subs {
			fmt.Fprintf(&b, "| [`%s`](#%s) | %s |\n", s.Name(), anchor(s), escape(s.Short))
		}
		b.WriteString("\n")
	}
	var walk func(*cobra.Command)
	walk = func(parent *cobra.Command) {
		for _, s := range subcommands(parent) {
			fmt.Fprintf(&b, "## %s\n\n", relativePath(s))
			description(&b, s)
			usage(&b, s)
			walk(s)
		}
	}
	walk(c)
	b.WriteString("Every command also accepts the [global options](index.md#global-options).\n")
	return b.Bytes()
}

func frontMatter(b *bytes.Buffer, title string) {
	fmt.Fprintf(b, "---\ntitle: %s\n---\n\n%s\n", title, generated)
}

// description writes the long description, led by the short one where the
// long one only adds detail: commands with subcommands, and those without
// a long description.
func description(b *bytes.Buffer, c *cobra.Command) {
	long := strings.TrimSpace(c.Long)
	if long == "" || c.HasAvailableSubCommands() {
		fmt.Fprintf(b, "%s.\n\n", escape(strings.TrimSuffix(strings.TrimSpace(c.Short), ".")))
	}
	if long != "" {
		fmt.Fprintf(b, "%s\n\n", escape(long))
	}
}

// usage writes the synopsis, examples and the command's own options.
func usage(b *bytes.Buffer, c *cobra.Command) {
	if c.Runnable() {
		codeBlock(b, c.UseLine())
	}
	if c.Example != "" {
		b.WriteString("**Examples**\n\n")
		codeBlock(b, c.Example)
	}
	if table := flagTable(c.NonInheritedFlags()); table != "" && c.HasParent() {
		b.WriteString("**Options**\n\n")
		b.WriteString(table)
	}
}

// flagTable lists the flags of a set as a Markdown table, leaving out
// --help.
func flagTable(fs *pflag.FlagSet) string {
	var b strings.Builder
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Name == "help" || f.Hidden {
			return
		}
		if b.Len() == 0 {
			b.WriteString("| Option | Description |\n|---|---|\n")
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		varname, usage := pflag.UnquoteUsage(f)
		if varname != "" {
			name += " " + varname
		}
		if !zeroDefault(f) {
			usage += fmt.Sprintf(" (default `%s`)", f.DefValue)
		}
		fmt.Fprintf(&b, "| `%s` | %s |\n", name, cell(escape(usage)))
	})
	if b.Len() > 0 {
		b.WriteString("\n")
	}
	return b.String()
}

// zeroDefault reports whether a flag's default is its type's zero value,
// which help output leaves out.
func zeroDefault(f *pflag.Flag) bool {
	switch f.DefValue {
	case "", "false", "0", "[]":
		return true
	}
	return false
}

// cell keeps text from ending a Markdown table cell.
func cell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

func codeBlock(b *bytes.Buffer, text string) {
	fmt.Fprintf(b, "```\n%s\n```\n\n", strings.TrimRight(text, "\n"))
}

// relativePath is a command's path below the root command.
func relativePath(c *cobra.Command) string {
	return strings.TrimPrefix(c.CommandPath(), c.Root().Name()+" ")
}

// anchor is the heading ID MkDocs gives a command's section.
func anchor(c *cobra.Command) string {
	return strings.ReplaceAll(relativePath(c), " ", "-")
}

// escape keeps help text from being read as HTML or emphasis.
func escape(s string) string {
	return strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "*", `\*`).Replace(s)
}
