// Code generated by schemagen from schema/daemon.yaml. DO NOT EDIT.

package config

import (
	"errors"
	"regexp"
	"time"
)

var reRetentionTime = regexp.MustCompile("^(?:(?:[01][0-9]|2[0-3]):[0-5][0-9])$")

// DaemonConfig holds the settings of /etc/pve/pve-rclone-backup/daemon.cfg.
type DaemonConfig struct {
	// LogLevel (log-level): Daemon log level.
	LogLevel string
	// AboutInterval (about-interval): How often remote quota is refreshed.
	AboutInterval time.Duration
	// HealthInterval (health-interval): How often remote connectivity is checked.
	HealthInterval time.Duration
	// CatalogResyncInterval (catalog-resync-interval): How often the catalogue is rebuilt from remote manifests.
	CatalogResyncInterval time.Duration
	// RetentionTime (retention-time): Local time of day at which scheduled retention runs.
	RetentionTime string
}

// daemonConfigKeys lists the properties defined by this schema.
var daemonConfigKeys = []string{"log-level", "about-interval", "health-interval", "catalog-resync-interval", "retention-time"}

// defaultDaemonConfig returns the settings with every default applied.
func defaultDaemonConfig() *DaemonConfig {
	return &DaemonConfig{
		LogLevel:              "info",
		AboutInterval:         mustDuration("15m"),
		HealthInterval:        mustDuration("5m"),
		CatalogResyncInterval: mustDuration("6h"),
		RetentionTime:         "05:00",
	}
}

// decodeDaemonConfig decodes raw properties on top of the defaults. Every
// problem is reported; consumed records the keys that were understood.
func decodeDaemonConfig(props map[string]Raw, consumed map[string]bool) (*DaemonConfig, error) {
	c := defaultDaemonConfig()
	var errs []error
	fail := func(key string, err error) { errs = append(errs, &PropertyError{Key: key, Err: err}) }

	if r, ok := props["log-level"]; ok {
		consumed["log-level"] = true
		if v, err := decodeEnum(r, []string{"debug", "info", "warn", "error"}); err != nil {
			fail("log-level", err)
		} else {
			c.LogLevel = v
		}
	}
	if r, ok := props["about-interval"]; ok {
		consumed["about-interval"] = true
		if v, err := decodeDuration(r, false); err != nil {
			fail("about-interval", err)
		} else {
			c.AboutInterval = v.Duration
		}
	}
	if r, ok := props["health-interval"]; ok {
		consumed["health-interval"] = true
		if v, err := decodeDuration(r, false); err != nil {
			fail("health-interval", err)
		} else {
			c.HealthInterval = v.Duration
		}
	}
	if r, ok := props["catalog-resync-interval"]; ok {
		consumed["catalog-resync-interval"] = true
		if v, err := decodeDuration(r, false); err != nil {
			fail("catalog-resync-interval", err)
		} else {
			c.CatalogResyncInterval = v.Duration
		}
	}
	if r, ok := props["retention-time"]; ok {
		consumed["retention-time"] = true
		if v, err := decodeString(r, reRetentionTime, 0); err != nil {
			fail("retention-time", err)
		} else {
			c.RetentionTime = v
		}
	}
	return c, errors.Join(errs...)
}
