// Code generated by schemagen from schema/node.yaml. DO NOT EDIT.

package config

import (
	"errors"
	"regexp"
	"time"
)

var reStagingDir = regexp.MustCompile("^(?:/[^\\s]*)$")

// NodeConfig holds the settings of /etc/pve/nodes/{node}/pve-rclone-backup.cfg.
type NodeConfig struct {
	// StagingDir (staging-dir): Directory for restore and fetch staging on this node.
	StagingDir string
	// StagingReserve (staging-reserve): Free space that staging must always leave on its filesystem.
	StagingReserve int64
	// UploadWorkers (upload-workers): Maximum concurrent uploads on this node across all storages.
	UploadWorkers int
	// ScanInterval (scan-interval): Interval of reconcile scans of source storages for missed archives.
	ScanInterval time.Duration
	// Inotify (inotify): Watch source storages for finished archives.
	Inotify bool
	// RestoreIOnice (restore-ionice): I/O scheduling class used for restore processes.
	RestoreIOnice string
}

// nodeConfigKeys lists the properties defined by this schema.
var nodeConfigKeys = []string{"staging-dir", "staging-reserve", "upload-workers", "scan-interval", "inotify", "restore-ionice"}

// defaultNodeConfig returns the settings with every default applied.
func defaultNodeConfig() *NodeConfig {
	return &NodeConfig{
		StagingDir:     "/var/lib/pve-rclone-backup/staging",
		StagingReserve: mustSize("10G"),
		UploadWorkers:  2,
		ScanInterval:   mustDuration("15m"),
		Inotify:        true,
		RestoreIOnice:  "best-effort:4",
	}
}

// decodeNodeConfig decodes raw properties on top of the defaults. Every
// problem is reported; consumed records the keys that were understood.
func decodeNodeConfig(props map[string]Raw, consumed map[string]bool) (*NodeConfig, error) {
	c := defaultNodeConfig()
	var errs []error
	fail := func(key string, err error) { errs = append(errs, &PropertyError{Key: key, Err: err}) }

	if r, ok := props["staging-dir"]; ok {
		consumed["staging-dir"] = true
		if v, err := decodeString(r, reStagingDir, 255); err != nil {
			fail("staging-dir", err)
		} else {
			c.StagingDir = v
		}
	}
	if r, ok := props["staging-reserve"]; ok {
		consumed["staging-reserve"] = true
		if v, err := decodeSize(r, nil); err != nil {
			fail("staging-reserve", err)
		} else {
			c.StagingReserve = v
		}
	}
	if r, ok := props["upload-workers"]; ok {
		consumed["upload-workers"] = true
		if v, err := decodeInt(r, new(int64(1)), new(int64(16))); err != nil {
			fail("upload-workers", err)
		} else {
			c.UploadWorkers = int(v)
		}
	}
	if r, ok := props["scan-interval"]; ok {
		consumed["scan-interval"] = true
		if v, err := decodeDuration(r, false); err != nil {
			fail("scan-interval", err)
		} else {
			c.ScanInterval = v.Duration
		}
	}
	if r, ok := props["inotify"]; ok {
		consumed["inotify"] = true
		if v, err := decodeBool(r); err != nil {
			fail("inotify", err)
		} else {
			c.Inotify = v
		}
	}
	if r, ok := props["restore-ionice"]; ok {
		consumed["restore-ionice"] = true
		if v, err := decodeEnum(r, []string{"best-effort:0", "best-effort:4", "best-effort:7", "idle"}); err != nil {
			fail("restore-ionice", err)
		} else {
			c.RestoreIOnice = v
		}
	}
	return c, errors.Join(errs...)
}
