// Code generated by schemagen from schema/storage.yaml. DO NOT EDIT.

package config

import (
	"errors"
	"regexp"
	"time"
)

var reRcloneRemote = regexp.MustCompile("^(?:[a-z][a-z0-9_-]{0,62})$")
var reRclonePath = regexp.MustCompile("^(?:[A-Za-z0-9][A-Za-z0-9._-]*(?:/[A-Za-z0-9][A-Za-z0-9._-]*)*)$")
var reRcloneSource = regexp.MustCompile("^(?:[a-z0-9][a-z0-9-]{0,31})$")

// Storage holds the settings of a rclone-backup storage.
type Storage struct {
	// ID is the storage ID (section name in storage.cfg).
	ID string

	// Remote (rclone-remote): Name of the transport remote configured with 'pve-rclone-backup remote add'.
	Remote string
	// Path (rclone-path): Repository base path inside the remote.
	Path string
	// Encryption (rclone-encryption): Client-side encryption of the repository (rclone crypt).
	Encryption string
	// Source (rclone-source): Namespace of this Proxmox VE installation inside the repository.
	Source string
	// ReplicateFrom (rclone-replicate-from): Local backup storages whose finished archives are replicated. Empty disables replication.
	ReplicateFrom []string
	// Guests (rclone-guests): Which guests are replicated: all, guests carrying one of rclone-tags, or rclone-vmids.
	Guests string
	// Tags (rclone-tags): Guest tags selecting guests when rclone-guests is "tagged".
	Tags []string
	// VMIDs (rclone-vmids): Guests replicated when rclone-guests is "listed".
	VMIDs []int
	// ExcludeVMIDs (rclone-exclude-vmids): Guests never replicated.
	ExcludeVMIDs []int
	// Backfill (rclone-backfill): Existing archives to replicate when replication is first enabled.
	Backfill string
	// MinInterval (rclone-min-interval): Skip an archive if the guest already has an offsite backup newer than this (e.g. 7d).
	MinInterval time.Duration
	// Supersede (rclone-supersede): Drop queued, not yet started uploads of older archives of the same guest.
	Supersede bool
	// Transfers (rclone-transfers): Number of archives uploaded concurrently.
	Transfers int
	// BwLimit (rclone-bwlimit): Upload bandwidth limit in rclone syntax, optionally a timetable such as "08:00,1M 23:00,off".
	BwLimit string
	// SegmentSize (rclone-segment-size): Size of the segments archives are split into.
	SegmentSize int64
	// VerifyInterval (rclone-verify-interval): Interval of listing-based verification (presence and provider checksums).
	VerifyInterval time.Duration
	// VerifyContent (rclone-verify-content): Interval of rolling download-based verification, or "off".
	VerifyContent Interval
	// VerifyBudget (rclone-verify-budget): Maximum bytes downloaded per day for content verification.
	VerifyBudget int64
	// MinAge (rclone-min-age): Retention never deletes offsite backups younger than this.
	MinAge time.Duration
	// KeepMin (rclone-keep-min): Retention keeps at least this many complete, verified backups per guest.
	KeepMin int
	// DeleteGrace (rclone-delete-grace): Deleted offsite backups are kept as tombstones for this long and can be restored.
	DeleteGrace time.Duration
	// MaxDeletes (rclone-max-deletes): Maximum number of backups a single retention run may delete.
	MaxDeletes int
	// Immutable (rclone-immutable): Refuse every deletion of offsite backups.
	Immutable bool

	// Base holds properties defined by PVE's base storage plugin.
	Base BaseOptions
}

// storageKeys lists the properties defined by this schema.
var storageKeys = []string{"rclone-remote", "rclone-path", "rclone-encryption", "rclone-source", "rclone-replicate-from", "rclone-guests", "rclone-tags", "rclone-vmids", "rclone-exclude-vmids", "rclone-backfill", "rclone-min-interval", "rclone-supersede", "rclone-transfers", "rclone-bwlimit", "rclone-segment-size", "rclone-verify-interval", "rclone-verify-content", "rclone-verify-budget", "rclone-min-age", "rclone-keep-min", "rclone-delete-grace", "rclone-max-deletes", "rclone-immutable"}

// defaultStorage returns the settings with every default applied.
func defaultStorage() *Storage {
	return &Storage{
		Path:           "pve-backups",
		Encryption:     "crypt",
		Guests:         "all",
		Tags:           SplitList("offsite"),
		Backfill:       "latest",
		MinInterval:    mustDuration("0"),
		Supersede:      true,
		Transfers:      2,
		SegmentSize:    mustSize("1G"),
		VerifyInterval: mustDuration("1d"),
		VerifyContent:  mustInterval("off"),
		VerifyBudget:   mustSize("100G"),
		MinAge:         mustDuration("7d"),
		KeepMin:        1,
		DeleteGrace:    mustDuration("7d"),
		MaxDeletes:     25,
		Immutable:      false,
	}
}

// decodeStorage decodes raw properties on top of the defaults. Every
// problem is reported; consumed records the keys that were understood.
func decodeStorage(props map[string]Raw, consumed map[string]bool) (*Storage, error) {
	c := defaultStorage()
	var errs []error
	fail := func(key string, err error) { errs = append(errs, &PropertyError{Key: key, Err: err}) }

	if r, ok := props["rclone-remote"]; ok {
		consumed["rclone-remote"] = true
		if v, err := decodeString(r, reRcloneRemote, 0); err != nil {
			fail("rclone-remote", err)
		} else {
			c.Remote = v
		}
	} else {
		fail("rclone-remote", errMissing)
	}
	if r, ok := props["rclone-path"]; ok {
		consumed["rclone-path"] = true
		if v, err := decodeString(r, reRclonePath, 128); err != nil {
			fail("rclone-path", err)
		} else {
			c.Path = v
		}
	}
	if r, ok := props["rclone-encryption"]; ok {
		consumed["rclone-encryption"] = true
		if v, err := decodeEnum(r, []string{"crypt", "none"}); err != nil {
			fail("rclone-encryption", err)
		} else {
			c.Encryption = v
		}
	}
	if r, ok := props["rclone-source"]; ok {
		consumed["rclone-source"] = true
		if v, err := decodeString(r, reRcloneSource, 0); err != nil {
			fail("rclone-source", err)
		} else {
			c.Source = v
		}
	} else {
		fail("rclone-source", errMissing)
	}
	if r, ok := props["rclone-replicate-from"]; ok {
		consumed["rclone-replicate-from"] = true
		if v, err := decodeStringList(r, ValidStorageID, "storage ID"); err != nil {
			fail("rclone-replicate-from", err)
		} else {
			c.ReplicateFrom = v
		}
	}
	if r, ok := props["rclone-guests"]; ok {
		consumed["rclone-guests"] = true
		if v, err := decodeEnum(r, []string{"all", "tagged", "listed"}); err != nil {
			fail("rclone-guests", err)
		} else {
			c.Guests = v
		}
	}
	if r, ok := props["rclone-tags"]; ok {
		consumed["rclone-tags"] = true
		if v, err := decodeStringList(r, ValidTag, "tag"); err != nil {
			fail("rclone-tags", err)
		} else {
			c.Tags = v
		}
	}
	if r, ok := props["rclone-vmids"]; ok {
		consumed["rclone-vmids"] = true
		if v, err := decodeVMIDList(r); err != nil {
			fail("rclone-vmids", err)
		} else {
			c.VMIDs = v
		}
	}
	if r, ok := props["rclone-exclude-vmids"]; ok {
		consumed["rclone-exclude-vmids"] = true
		if v, err := decodeVMIDList(r); err != nil {
			fail("rclone-exclude-vmids", err)
		} else {
			c.ExcludeVMIDs = v
		}
	}
	if r, ok := props["rclone-backfill"]; ok {
		consumed["rclone-backfill"] = true
		if v, err := decodeEnum(r, []string{"none", "latest", "all"}); err != nil {
			fail("rclone-backfill", err)
		} else {
			c.Backfill = v
		}
	}
	if r, ok := props["rclone-min-interval"]; ok {
		consumed["rclone-min-interval"] = true
		if v, err := decodeDuration(r, false); err != nil {
			fail("rclone-min-interval", err)
		} else {
			c.MinInterval = v.Duration
		}
	}
	if r, ok := props["rclone-supersede"]; ok {
		consumed["rclone-supersede"] = true
		if v, err := decodeBool(r); err != nil {
			fail("rclone-supersede", err)
		} else {
			c.Supersede = v
		}
	}
	if r, ok := props["rclone-transfers"]; ok {
		consumed["rclone-transfers"] = true
		if v, err := decodeInt(r, new(int64(1)), new(int64(8))); err != nil {
			fail("rclone-transfers", err)
		} else {
			c.Transfers = int(v)
		}
	}
	if r, ok := props["rclone-bwlimit"]; ok {
		consumed["rclone-bwlimit"] = true
		if v, err := decodeString(r, nil, 256); err != nil {
			fail("rclone-bwlimit", err)
		} else {
			c.BwLimit = v
		}
	}
	if r, ok := props["rclone-segment-size"]; ok {
		consumed["rclone-segment-size"] = true
		if v, err := decodeSize(r, new(int64(67108864))); err != nil {
			fail("rclone-segment-size", err)
		} else {
			c.SegmentSize = v
		}
	}
	if r, ok := props["rclone-verify-interval"]; ok {
		consumed["rclone-verify-interval"] = true
		if v, err := decodeDuration(r, false); err != nil {
			fail("rclone-verify-interval", err)
		} else {
			c.VerifyInterval = v.Duration
		}
	}
	if r, ok := props["rclone-verify-content"]; ok {
		consumed["rclone-verify-content"] = true
		if v, err := decodeDuration(r, true); err != nil {
			fail("rclone-verify-content", err)
		} else {
			c.VerifyContent = v
		}
	}
	if r, ok := props["rclone-verify-budget"]; ok {
		consumed["rclone-verify-budget"] = true
		if v, err := decodeSize(r, nil); err != nil {
			fail("rclone-verify-budget", err)
		} else {
			c.VerifyBudget = v
		}
	}
	if r, ok := props["rclone-min-age"]; ok {
		consumed["rclone-min-age"] = true
		if v, err := decodeDuration(r, false); err != nil {
			fail("rclone-min-age", err)
		} else {
			c.MinAge = v.Duration
		}
	}
	if r, ok := props["rclone-keep-min"]; ok {
		consumed["rclone-keep-min"] = true
		if v, err := decodeInt(r, new(int64(0)), nil); err != nil {
			fail("rclone-keep-min", err)
		} else {
			c.KeepMin = int(v)
		}
	}
	if r, ok := props["rclone-delete-grace"]; ok {
		consumed["rclone-delete-grace"] = true
		if v, err := decodeDuration(r, false); err != nil {
			fail("rclone-delete-grace", err)
		} else {
			c.DeleteGrace = v.Duration
		}
	}
	if r, ok := props["rclone-max-deletes"]; ok {
		consumed["rclone-max-deletes"] = true
		if v, err := decodeInt(r, new(int64(0)), nil); err != nil {
			fail("rclone-max-deletes", err)
		} else {
			c.MaxDeletes = int(v)
		}
	}
	if r, ok := props["rclone-immutable"]; ok {
		consumed["rclone-immutable"] = true
		if v, err := decodeBool(r); err != nil {
			fail("rclone-immutable", err)
		} else {
			c.Immutable = v
		}
	}
	return c, errors.Join(errs...)
}
