// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"fmt"
	"strings"
)

// docIntros introduce each reference page.
var docIntros = map[string]string{
	"storage": "Properties of `rclone-backup` storages in `/etc/pve/storage.cfg`. " +
		"`pve-rclone-backup storage init` sets them when it adds a storage. Change them with " +
		"`pve-rclone-backup storage set <storage> <property>=<value>` or `pvesm set <storage> --<property> <value>`, " +
		"and reset one to its default with `pvesm set <storage> --delete <property>`. " +
		"The daemon picks up changes on its own. [Storages](../guide/storages.md) explains how to use them.",
	"node": "Settings of the daemon on one node, in `/etc/pve/nodes/<node>/pve-rclone-backup.cfg`. " +
		keyValueFile,
	"daemon": "Settings shared by the daemons on all nodes of a cluster, in `/etc/pve/pve-rclone-backup/daemon.cfg`. " +
		keyValueFile,
}

const keyValueFile = "The file is optional: a missing file or setting means the default. " +
	"Write one `key: value` per line; lines starting with `#` are comments.\n\n" +
	"The daemon reads the file when it starts, so restart it after a change: " +
	"`systemctl restart pve-rclone-backupd`. If the file is invalid, the daemon uses the defaults " +
	"and `pve-rclone-backup status` reports the problem."

// docTitles name each reference page.
var docTitles = map[string]string{
	"storage": "Storage properties",
	"node":    "Node settings",
	"daemon":  "Daemon settings",
}

// baseOptionDocs describes what PVE's own storage properties mean for this
// storage type.
var baseOptionDocs = map[string]string{
	"content": "`backup`, the only content type of the storage.",
	"nodes": "Limits the storage to these nodes. Other nodes neither list its backups nor replicate to it. " +
		"Unset means all nodes.",
	"disable": "`1` disables the storage: PVE does not use it and the daemon does not replicate to it.",
	"shared":  "Always `1`, set automatically: every node reaches the same repository.",
	"prune-backups": "The offsite retention policy, in PVE's syntax (for example `keep-last=3,keep-weekly=4`). " +
		"Unset keeps every backup. See [Retention](../guide/retention.md).",
	"max-protected-backups": "PVE's limit on protected backups per guest, applied when backups are " +
		"protected through PVE.",
	"bwlimit": "PVE's bandwidth limits in KiB/s for operations PVE runs on the storage. " +
		"Uploads are limited by `rclone-bwlimit` instead.",
}

func genDoc(s *schemaFile, j job) ([]byte, error) {
	title, intro := docTitles[j.schema], docIntros[j.schema]
	if title == "" || intro == "" {
		return nil, fmt.Errorf("no documentation title or introduction for schema %s", j.schema)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %s\n---\n\n", title)
	fmt.Fprintf(&b, "<!-- Code generated by schemagen from schema/%s.yaml. DO NOT EDIT; run make generate. -->\n\n", j.schema)
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", title, intro)

	column := "Setting"
	if j.storage {
		column = "Property"
	}
	fmt.Fprintf(&b, "| %s | Default | Description |\n|---|---|---|\n", column)
	for _, p := range s.Properties {
		fmt.Fprintf(&b, "| [`%s`](#%s) | %s | %s |\n", p.Key, p.Key, cell(docDefault(p)), cell(p.Description))
	}
	b.WriteString("\n")

	for _, p := range s.Properties {
		fmt.Fprintf(&b, "## `%s`\n\n**%s.** %s\n\n", p.Key, p.Title, p.Description)
		fmt.Fprintf(&b, "- Value: %s\n", docType(p))
		fmt.Fprintf(&b, "- Default: %s\n", docDefault(p))
		if when := docOption(p); when != "" {
			fmt.Fprintf(&b, "- %s\n", when)
		}
		b.WriteString("\n")
	}

	if len(s.BaseOptions) > 0 {
		b.WriteString("## Proxmox VE storage properties\n\nThe storage also accepts these properties that all Proxmox VE storages share.\n\n")
		b.WriteString("| Property | Meaning |\n|---|---|\n")
		for _, o := range s.BaseOptions {
			d, ok := baseOptionDocs[o]
			if !ok {
				return nil, fmt.Errorf("base option %s is not documented", o)
			}
			fmt.Fprintf(&b, "| `%s` | %s |\n", o, cell(d))
		}
	}
	return []byte(strings.TrimRight(b.String(), "\n") + "\n"), nil
}

func docType(p property) string {
	switch p.Type {
	case "boolean":
		return "`1` (yes) or `0` (no)."
	case "integer":
		switch {
		case p.Minimum != nil && p.Maximum != nil:
			return fmt.Sprintf("an integer from %d to %d.", *p.Minimum, *p.Maximum)
		case p.Minimum != nil:
			return fmt.Sprintf("an integer of at least %d.", *p.Minimum)
		}
		return "an integer."
	case "enum":
		quoted := make([]string, len(p.Values))
		for i, v := range p.Values {
			quoted[i] = "`" + v + "`"
		}
		return "one of " + strings.Join(quoted, ", ") + "."
	case "size":
		t := "a size in bytes with an optional binary unit `K`, `M`, `G` or `T`, such as `512M`"
		if p.Minimum != nil {
			t += ", of at least `" + humanSize(*p.Minimum) + "`"
		}
		return t + "."
	case "duration":
		t := "a duration: a number followed by `s`, `m`, `h`, `d` or `w` (seconds to weeks), such as `7d`"
		if p.AllowOff {
			t += ", or `off`"
		}
		return t + "."
	case "list":
		what := map[string]string{"storage-id": "storage IDs", "tag": "guest tags", "vmid": "guest IDs (VMIDs)"}[p.Element]
		return "a list of " + what + ", separated by commas, semicolons or spaces."
	}
	t := "text"
	if p.Pattern != "" {
		t += " matching the regular expression `" + p.Pattern + "`"
	}
	if p.MaxLength > 0 {
		t += fmt.Sprintf(", at most %d characters", p.MaxLength)
	}
	return t + "."
}

func docDefault(p property) string {
	if p.Default == nil {
		return "none"
	}
	return "`" + defaultString(p) + "`"
}

func docOption(p property) string {
	switch p.Option {
	case "required":
		return "Required."
	case "fixed":
		return "Required. Set when the storage is created; it cannot be changed afterwards."
	case "fixed-optional":
		return "Set when the storage is created; it cannot be changed afterwards."
	}
	return ""
}

// humanSize formats a byte count in the largest binary unit that divides it.
func humanSize(n int64) string {
	for _, u := range []struct {
		suffix string
		shift  uint
	}{{"T", 40}, {"G", 30}, {"M", 20}, {"K", 10}} {
		if n >= 1<<u.shift && n%(1<<u.shift) == 0 {
			return fmt.Sprintf("%d%s", n>>u.shift, u.suffix)
		}
	}
	return fmt.Sprint(n)
}

// cell escapes text for a Markdown table cell.
func cell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
